services:
  - type: web
    name: flask-text-reader
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: text-reader-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: GUNICORN_CMD_ARGS
        value: "--timeout 120 --workers 1 --threads 3"

databases:
  - name: text-reader-db
    databaseName: text_reader
    user: text_reader_user
    plan: free
